[build]
  functions = "src/" # Make sure this path matches your functions directory
  publish = "build" # Adjust if you have a build directory

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
  force = true
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
